config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  
  
  resources :products do
    resources :comments
  end

   
 
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/landing_page'

  post 'static_pages/thank_you'

  resources :orders, only: [:index, :show, :create, :destroy]

  root 'static_pages#landing_page'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
    
    if user.admin?
        can :manage, :all
        can :destroy, Comment
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name, presence: true
	has_many :orders
	has_many :comments
	
	def average_rating
	  comments.average(:rating).to_f
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	
end

app/controllers/Orders_Controller.rb
class OrdersController < ApplicationController

 before_filter :authenticate_user!

def index
end

def show
end

def create
end

def destroy
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
  redirect_to main_app.root_url, :alert => exception.message
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id]) 
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private

    def comment_params
      params.require(:comment).permit(:user_id, :body, :rating)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
    @products = Product.limit(3)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/static_pages/landing_page", notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	 
  end


def landing_page 
	@featured_product = Product.first
	@products = Product.limit(3)
end

def thank_you
  @name = params[:name]
  @email = params[:email]
  @message = params[:message]
  UserMailer.contact_form(@email, @name, @message).deliver_now
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <hr>
  <p>
    <%= comment.user.first_name %>  <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if signed_in? && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
  <div class="rated" data-score="<%= comment.rating %>"></div>
  <p><%= comment.body %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nameofapp</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>

<body>
<div id="wrap">

<nav class="container-fluid">
	<div class="row text-center">
	<ul class="nav nav-pills center-pills">
		<li>
          <%= link_to 'Home', root_path %>
        </li>
		<li>
          <%= link_to 'About', static_pages_about_path %>
        </li>
		 <li><%= link_to "Products", products_path %></li>
		  <li>
          <%= link_to 'Contact', static_pages_contact_path %>
        </li>
        <li>
          <%= form_tag("/products", method: "get", :class => "form_nav") do %>
            <%= label_tag(:q, "Search for:") %>
            <%= text_field_tag(:q) %>
            <%= submit_tag("Search") %>
          <% end %>
        </li>
	</ul>
  <ul class="nav pull-right">
    <li>
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </li>
  </ul>
</div>
</nav>


<% if alert %>
    <p id="alert" class="alert alert-info"><%= notice %></p>
<% end %>

<% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
<% end %>

<%= yield %>

<footer class="container-fluid">	
	<div class="row foot">
		<p class="col-sm-6">&copy;	Jack Doyle 2014</p>
		<div class="twitter col-sm-6">
		<a href="https://twitter.com/OdoyleRules13" class="twitter-follow-button" data-show-count="false" data-size="large" data-show-screen-name="false">Follow @OdoyleRules13</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

</div>
	</footer>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
    <div class="field">
  <%= f.label :colour %><br>
  <%= f.text_field :colour %>
</div>
  <div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build],remote: true) do |f| %>
    <div class="form-group">
      <p>
        <%= f.label :body, "Comments" %><br>
        <%= f.text_area :body, class: "form-control" %>
      </p>
    </div>
    <div class="form-group">
      <p>
        <%= f.label :rating %><br>
        <div class="rating"></div>
      </p>  
    </div>
    <p>
      <%= f.submit "Submit", class: "btn btn-danger", id: "revsubmit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% @products.each do |product| %>
      <div class="row col-xs-offset-1">
        <p class="col-xs-2"><%= product.name %></p>
        <p class="col-xs-2"><%= product.description %></p>
        <p class="col-xs-2"><%= image_tag(product.image_url, :class => 'img-thumbnail') %></p>
        <p class="col-xs-2"><%= product.colour %></p>
        <p class="col-xs-2"><%= product.price %></p>
      </div>
      <p><%= link_to 'Show', product %>
        <%= link_to 'Edit', edit_product_path(product) %>
        <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></p>
    <% end %>
</div>

app/views/products/_show_reviews.html.erb
<p id="notice"><%= notice %></p>
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
            <% if signed_in? && current_user.admin? %>
            	<span class="glyphicon glyphicon-trash"></span> 
            	<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
        </div>
    <% end %>
    <%= will_paginate @comments %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Our Products</h1>

<div class="container">
  <div class="row col-xs-offset-1">
      <h4 class="col-xs-2">Name</h4>
      <h4 class="col-xs-2">Description</h4>
      <h4 class="col-xs-2">Image url</h4>
      <h4 class="col-xs-2">Colour</h4>
      <h4 class="col-xs-2">Price</h4>
      <h4 colspan="3"></h4>
  </div>


      <%= render @products %>


<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row products">

      <div class="col-xs-12 col-md-6 products_left">
        <a href="<%= @product.image_url %>" class="thumbnail" alt="Responsive image">
      <%= image_tag(@product.image_url, class: "img-zoom", data_zoom_image: @product.image_url) %>
        </a>
      </div>
      
      <div class="col-xs-12 col-md-6 products_right">
        <p>
          <strong>Name:</strong>
          <%= @product.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @product.description %>
        </p>

        <p>
          <strong>Color:</strong>
          <%= @product.colour %>
        </p>

        <p>
          <strong>Price:</strong>
          <%= @product.price %>
        </p>
      </div>
  </div>
<div class="container">
    <%= render partial: 'new_comment' %>
      <div class="show-index-rating">
        <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
      </div>
   <%= render 'show_reviews' %></div>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>Jack's Bikes is a full service bike shop located in Buffalo, NY. We are dedicated to serving our customers with a wide variety of inventory to accomodate any need you may have</p>

app/views/static_pages/contact.html.erb
<h1 class="contact_title">Contact Me</h1>
<%= flash[:notice] %>

<%= form_tag("/static_pages/thank_you") do %>
<div class="row contact_form">
    <div class="col-md-4">
        <div class="form-group">
            <%= label_tag :name, "Name" %>
            <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
        </div>      
        <div class="form-group">
            <%= label_tag :email, "Email Address" %>
            <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
        </div>
        <div class="form-group">
            <%= label_tag :message, "Message" %>
            <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
        </div>  
        <%= submit_tag "Send", :class => 'contact_button' %>       
    </div>
</div>

<% end %>

app/views/static_pages/index.html.erb
<div class="content">	
<h1>320 Designs</h1>
<h2>Custom clothing designs</h2>
<a>SHOP</a>
</div>

app/views/static_pages/landing_page.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
       <%= image_tag("sampleT", :alt => "rss feed") %>
    </div>

    <div class="item">
      <%= image_tag("urban", :alt => "rss feed") %>
    </div>

    <div class="item">
       <%= image_tag("sampleT", :alt => "rss feed") %>
    </div>

    <div class="item">
       <%= image_tag("sampleT", :alt => "rss feed") %>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


<h2>Featured Products</h2>
<p>A colection of popular products from our most talented designers</p>
<div class="thumbnail-grid flex">
  <a href="#">
    <figure class="i1">
      <figcaption>Item 1</figcaption>
    </figure>
  </a>
  <a href="#" class="flex-item">
    <figure class="i2">
      <figcaption>Item 2</figcaption>
    </figure>
  </a>
  <a href="#" class="flex-item">
    <figure class="i3">
      <figcaption>Item 3</figcaption>
    </figure>
  </a>
</div>

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>